backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Message", name: "hero", widget: "text" }
      - file: "about.html"
        label: "About"
        name: "about"
        fields:
          - { label: "About Title", name: "title", widget: "string" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "What We Do", name: "what_we_do", widget: "text" }
          - { label: "Our Principles", name: "principles", widget: "text" }
      - file: "services.html"
        label: "Research & Innovation"
        name: "services"
        fields:
          - { label: "Intro Text", name: "intro", widget: "text" }
          - { label: "Capabilities", name: "capabilities", widget: "list" }
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Contact Title", name: "title", widget: "string" }
          - { label: "Team Members", name: "team", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Role", name: "role", widget: "string" },
              { label: "Degree", name: "degree", widget: "string" },
              { label: "Email", name: "email", widget: "string" }
            ] }
